version: '3.8'

services:
  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"  # Map the port from the host to the container
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    expose:
      - "6379"

networks:
  default:
    driver: bridge
