name: Build and deploy container app to Azure Web App - blockchatapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name blockchatapi

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: blockchatapi.azurecr.io/custom-openai-api-endpoint:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blockchatapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cac38c624594471e983ed3708eba41dd }}
        images: 'blockchatapi.azurecr.io/custom-openai-api-endpoint:${{ github.sha }}'
